import sys

path = '/Users/chandan/Desktop/AuthPrivacyChain_V2/src/App.tsx'
with open(path, 'r') as f:
    content = f.read()

# Reconstruct the login/signup block perfectly
start_marker = "if (view === 'login' || view === 'signup') {"
idx_start = content.find(start_marker)

if idx_start != -1:
    # Find the end of this block (the next if or the return null)
    end_marker = "if (view === 'home')"
    idx_end = content.find(end_marker, idx_start)
    
    if idx_end != -1:
        new_block = "if (view === 'login' || view === 'signup') {\n"
        new_block += "    return (\n"
        new_block += "      <>\n"
        new_block += "        {fullScreenAlert && (\n"
        new_block += "          <div className=\"geofence-shield-overlay\">\n"
        new_block += "            <div className=\"cyber-grid-red\"></div>\n"
        new_block += "            <div className=\"cyber-grid-blue\"></div>\n"
        new_block += "            <div className=\"laser-scanner-red\"></div>\n"
        new_block += "            <div className=\"laser-scanner-blue\"></div>\n"
        new_block += "            <div className=\"shield-container\">\n"
        new_block += "              <div className=\"shield-glow-ring\"></div>\n"
        new_block += "              <div className=\"shield-icon-wrap\">\n"
        new_block += "                <span className=\"shield-main-icon\">🛡️</span>\n"
        new_block += "                <div className=\"shield-scanner-line\"></div>\n"
        new_block += "              </div>\n"
        new_block += "              <div className=\"shield-content\">\n"
        new_block += "                <h1 className=\"shield-title\">PERIMETER BREACH</h1>\n"
        new_block += "                <div className=\"shield-separator\">\n"
        new_block += "                  <div className=\"sep-red\"></div>\n"
        new_block += "                  <div className=\"sep-blue\"></div>\n"
        new_block += "                </div>\n"
        new_block += "                <p className=\"shield-msg\">\n"
        new_block += "                  <span className=\"glitch-text\" data-text=\"ACCESS DENIED\">ACCESS DENIED</span>\n"
        new_block += "                  <br />\n"
        new_block += "                  NODE LOCATION: <span style={{color: '#ef4444'}}>FOREIGN_ZONE</span>\n"
        new_block += "                  <br />\n"
        new_block += "                  Your connection was intercepted by the Indian Geographic Firewall.\n"
        new_block += "                </p>\n"
        new_block += "                <div className=\"forensic-meta\">\n"
        new_block += "                  <div className=\"meta-item\"><span className=\"m-label\">PROTOCOL</span><span className=\"m-val\">GEO-BLOCK</span></div>\n"
        new_block += "                  <div className=\"meta-item\"><span className=\"m-label\">ORIGIN</span><span className=\"m-val red\">BLOCKED</span></div>\n"
        new_block += "                </div>\n"
        new_block += "                <button className=\"shield-dismiss-btn\" onClick={() => setFullScreenAlert(false)}>\n"
        new_block += "                  ACKNOWLEDGE SECURITY PROTOCOL\n"
        new_block += "                </button>\n"
        new_block += "              </div>\n"
        new_block += "            </div>\n"
        new_block += "          </div>\n"
        new_block += "        )}\n"
        new_block += "\n"
        new_block += "        <div className=\"main-portal\">\n"
        new_block += "          <div className=\"cyber-grid-bg\"></div>\n"
        new_block += "          <button type=\"button\" className=\"top-right-ledger-btn\" onClick={() => setShowLedger(true)}>\n"
        new_block += "            <span className=\"pulse-dot\"></span> LIVE NETWORK LEDGER\n"
        new_block += "          </button>\n"
        new_block += "          <div className=\"cloud-container\">\n"
        new_block += "            <div className=\"asset-cloud c1\">☁️</div>\n"
        new_block += "            <div className=\"asset-cloud c2\">☁️</div>\n"
        new_block += "            <div className=\"asset-cloud c3\">☁️</div>\n"
        new_block += "          </div>\n"
        new_block += "\n"
        new_block += "          <div className=\"auth-card\">\n"
        new_block += "            <div className=\"logo-center-box\"><img src={LOGO_PATH} alt=\"Brand Logo\" className=\"brand-logo-main\" /></div>\n"
        new_block += "            <h1>AuthPrivacyChain <span>V2</span></h1>\n"
        new_block += "            <p className=\"status-label\">QUANTUM GATEWAY ACTIVE</p>\n"
        new_block += "\n"
        new_block += "            <div className=\"toggle-switcher\">\n"
        new_block += "              <div className={`switch-pill ${role === 'admin' ? 'pos-admin' : 'pos-user'}`}></div>\n"
        new_block += "              <button type=\"button\" className={role === 'user' ? 'active' : ''} onClick={() => { setRole('user'); setIdentity(''); setPassword(''); }}>USER GATEWAY</button>\n"
        new_block += "              <button type=\"button\" className={role === 'admin' ? 'active' : ''} onClick={() => { setRole('admin'); setIdentity(''); setPassword(''); }}>ADMIN MODE</button>\n"
        new_block += "            </div>\n"
        new_block += "\n"
        new_block += "            <form onSubmit={handleAction}>\n"
        new_block += "              {view === 'signup' && (\n"
        new_block += "                <div className=\"cyber-field\">\n"
        new_block += "                  <label>FULL LEGAL IDENTITY</label>\n"
        new_block += "                  <input type=\"text\" placeholder=\"Enter Name...\" required value={legalName} onChange={(e) => setLegalName(e.target.value)} autoComplete=\"off\" />\n"
        new_block += "                </div>\n"
        new_block += "              )}\n"
        new_block += "              <div className=\"cyber-field\">\n"
        new_block += "                <label>{role === 'admin' ? 'ADMINISTRATOR TOKEN' : (view === 'signup' ? 'PHONE NUMBER' : 'UNIQUE ID')}</label>\n"
        new_block += "                <input type=\"text\" placeholder={role === 'admin' ? \"ADM-777\" : \"Enter ID...\"} required value={identity} onChange={(e) => setIdentity(e.target.value)} autoComplete=\"off\" />\n"
        new_block += "              </div>\n"
        new_block += "              <div className=\"cyber-field\">\n"
        new_block += "                <label>ENCRYPTION PASSPHRASE</label>\n"
        new_block += "                <input type=\"password\" placeholder=\"••••••••\" required value={password} onChange={(e) => setPassword(e.target.value)} autoComplete=\"off\" />\n"
        new_block += "              </div>\n"
        new_block += "              <button type=\"submit\" className=\"cyber-btn\">{view === 'login' ? 'ESTABLISH LINK' : 'CREATE ACCOUNT'}</button>\n"
        new_block += "              <div className=\"auth-footer-links\">\n"
        new_block += "                <button type=\"button\" className=\"signup-link\" onClick={() => { setView(view === 'login' ? 'signup' : 'login'); setIdentity(''); setPassword(''); }}>\n"
        new_block += "                  {view === 'login' ? '// New here? Join the family.' : '// Back to Login'}\n"
        new_block += "                </button>\n"
        new_block += "                <button type=\"button\" className=\"v1-shortcut\" onClick={() => setShowRecoveryModal(true)}>[ MASTER KEY ] QUICK ACCESS</button>\n"
        new_block += "              </div>\n"
        new_block += "            </form>\n"
        new_block += "          </div>\n"
        new_block += "\n"
        new_block += "          <style>{`\n"
        new_block += "            .main-portal { min-height: 100vh; background: #02040a; display: flex; flex-direction: column; align-items: center; justify-content: center; position: relative; overflow: hidden; font-family: sans-serif; }\n"
        new_block += "            .cyber-grid-bg { position: absolute; inset: 0; background-image: linear-gradient(rgba(37,99,235,0.12) 1px, transparent 1px), linear-gradient(90deg, rgba(37,99,235,0.12) 1px, transparent 1px); background-size: 50px 50px; z-index: 1; }\n"
        new_block += "            .cloud-container { position: fixed; inset: 0; z-index: 5; pointer-events: none; }\n"
        new_block += "            .asset-cloud { position: absolute; display: flex; align-items: center; justify-content: center; font-size: 280px; opacity: 0.8; user-select: none; filter: drop-shadow(0 20px 40px rgba(0,0,0,0.5)); z-index: 5; }\n"
        new_block += "            .c1 { top: 5%; left: 5%; transform: rotate(-15deg); animation: float 12s infinite alternate ease-in-out; }\n"
        new_block += "            .c2 { bottom: 10%; right: 8%; font-size: 350px; transform: rotate(10deg); animation: float 18s infinite alternate-reverse ease-in-out; }\n"
        new_block += "            .c3 { top: 20%; right: 20%; font-size: 150px; opacity: 0.5; transform: rotate(5deg); animation: float 25s infinite alternate ease-in-out; }\n"
        new_block += "            @keyframes float { from { transform: translate(0, 0) rotate(-5deg); } to { transform: translate(30px, -20px) rotate(5deg); } }\n"
        new_block += "            .auth-card { width: 100%; max-width: 440px; background: rgba(10, 10, 10, 0.85); backdrop-filter: blur(25px); border: 1px solid rgba(255,255,255,0.1); border-radius: 44px; padding: 55px; z-index: 10; text-align: center; color: white; box-shadow: 0 20px 50px rgba(0,0,0,0.5); }\n"
        new_block += "            .logo-center-box { display: flex; justify-content: center; margin-bottom: 20px; }\n"
        new_block += "            .brand-logo-main { width: 90px; height: 90px; object-fit: contain; }\n"
        new_block += "            h1 { font-size: 26px; font-weight: 900; margin: 0; } h1 span { color: #3b82f6; }\n"
        new_block += "            .status-label { font-size: 9px; letter-spacing: 5px; color: #3b82f6; margin-bottom: 40px; font-weight: 900; }\n"
        new_block += "            .toggle-switcher { display: flex; background: #000; padding: 5px; border-radius: 18px; margin-bottom: 35px; border: 1px solid rgba(255,255,255,0.04); position: relative; }\n"
        new_block += "            .toggle-switcher button { flex: 1; padding: 12px; background: transparent; border: none; font-size: 10px; font-weight: 900; color: #4b5563; z-index: 2; cursor: pointer; }\n"
        new_block += "            .toggle-switcher button.active { color: #fff; }\n"
        new_block += "            .switch-pill { position: absolute; top: 5px; bottom: 5px; width: calc(50% - 5px); background: #2563eb; border-radius: 14px; transition: 0.5s; }\n"
        new_block += "            .pos-admin { left: 50%; } .pos-user { left: 5px; }\n"
        new_block += "            .cyber-field { text-align: left; margin-bottom: 22px; }\n"
        new_block += "            .cyber-field label { display: block; font-size: 9px; font-weight: 800; color: #64748b; margin-bottom: 10px; margin-left: 15px; }\n"
        new_block += "            .cyber-field input { width: 100%; padding: 18px 24px; border-radius: 20px; background: #000; border: 1px solid rgba(255,255,255,0.08); color: #fff; outline: none; box-sizing: border-box; }\n"
        new_block += "            .cyber-btn { width: 100%; padding: 18px; border-radius: 20px; border: none; background: #fff; color: #000; font-weight: 900; cursor: pointer; font-size: 11px; }\n"
        new_block += "            .auth-footer-links { margin-top: 25px; display: flex; flex-direction: column; gap: 12px; }\n"
        new_block += "            .signup-link, .v1-shortcut { background: none; border: none; font-size: 10px; font-weight: 900; cursor: pointer; }\n"
        new_block += "            .signup-link { color: #4b5563; } .v1-shortcut { color: #3b82f6; }\n"
        new_block += "            .master-modal-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.9); display: flex; align-items: center; justify-content: center; z-index: 1000; }\n"
        new_block += "            .master-modal-card { background: #0a0a0a; border: 2px solid #2563eb; padding: 40px; border-radius: 30px; text-align: center; max-width: 400px; color: white; }\n"
        new_block += "            .key-display { background: #000; color: #3b82f6; padding: 20px; font-family: monospace; border-radius: 10px; margin: 20px 0; border: 1px dashed #333; font-size: 18px; font-weight: bold; word-break: break-all; }\n"
        new_block += "            .top-right-ledger-btn { position: absolute; top: 30px; right: 40px; background: transparent; border: none; color: #22c55e; padding: 12px 24px; font-weight: 900; cursor: pointer; z-index: 100; font-size: 15px; letter-spacing: 1px; display: flex; align-items: center; }\n"
        new_block += "            .pulse-dot { display: inline-block; width: 12px; height: 12px; background: #22c55e; border-radius: 50%; box-shadow: 0 0 10px #22c55e, 0 0 20px #22c55e; margin-right: 12px; animation: pulse-dot-anim 1.5s infinite; }\n"
        new_block += "            @keyframes pulse-dot-anim { 0% { transform: scale(1); opacity: 1; } 50% { transform: scale(1.5); opacity: 0.5; } 100% { transform: scale(1); opacity: 1; } }\n"
        new_block += "          `}</style>\n"
        new_block += "        </div>\n"
        new_block += "      </>\n"
        new_block += "    );\n"
        new_block += "  }\n\n  "
        
        new_content = content[:idx_start] + new_block + content[idx_end:]
        with open(path, 'w') as f:
            f.write(new_content)
        print("SUCCESS")
    else:
        print("FAILED: End marker not found")
else:
    print("FAILED: Start marker not found")
